### ISSUE TITLE
Export Log To AWS CloudWatch

### ISSUE THREAD

**Issue by jerrychong25** [mulesoft-labs/mule-amazon-cloudwatch-connector#1]
Hi all,

I am planning to export logging from MuleSoft CloudHub to AWS CloudWatch.

I saw there is one AWS CloudWatch Connector in GitHub:
https://github.com/mulesoft-labs/mule-amazon-cloudwatch-connector/tree/master/mule-cloudwatch-connector

Is there any examples on how to implement this?

And which AWS CloudWatch features is supported in this connector?

Thanks.

**Comment by jerrychong25** [comment]
@MonicaAbreo @MonicaAbreoA @fcatae @germandavid85 @jstoiko @runnabro @vromero 

Hi all,

Any ideas on this?

Thanks.

**Comment by jerrychong25** [comment]
Hi all,

Any updates on this?

Thanks.

**Comment by MonicaAbreo** [comment]
Hi @jerrychong25 , Sorry for the delay response.  We were developing this connector as an experiment to pull CloudWatch metrics during performance tests but we dropped this initiative a long time ago and we are no longer supporting it. However, we think it's fine to fork the repository and continue to add new features as needed.

About the features, the connector supports the following functionalities: 
DescribeAlarms
DescribeAlarmHistory
DescribeAlarmsForMetric
ListMetrics
GetMetricData
PutMetricData
GetMetricStatistics
We use https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Operations.html as a guide for the request and the Mulesoft documentation to create the connector.
Please talk with @keertipatil 

Regards

**Comment by jerrychong25** [comment]
> Hi @jerrychong25 , Sorry for the delay response. We were developing this connector as an experiment to pull CloudWatch metrics during performance tests but we dropped this initiative a long time ago and we are no longer supporting it. However, we think it's fine to fork the repository and continue to add new features as needed.
> 
> About the features, the connector supports the following functionalities:
> DescribeAlarms
> DescribeAlarmHistory
> DescribeAlarmsForMetric
> ListMetrics
> GetMetricData
> PutMetricData
> GetMetricStatistics
> We use https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_Operations.html as a guide for the request and the Mulesoft documentation to create the connector.
> Please talk with @keertipatil
> 
> Regards

Hi @MonicaAbreo 

Thanks for the useful info.

Will check with @keertipatil if have any questions on this.

Thanks again!
